-- 010 — audit_journal. Table 9 of 9.
--
-- One append-only journal row per thing that happened. The append-only property is not a
-- convention here: 011 revokes UPDATE and DELETE on this table and `pnpm migrate` asserts
-- against information_schema.role_table_grants that the revocation actually took effect.
--
-- `sequence` and `prev_hash` chain the rows so a gap is visible: sequence is monotonic and
-- unique, and no two rows may claim the same predecessor.
--
-- THE FIREWALL, AS A CONSTRAINT. A model is an actor and is recorded as one — but a model
-- actor may appear ONLY on the events its two permitted call sites can produce:
-- normalisation during ingestion, and a residual proposal. `hold_released`,
-- `decision_recorded` and `tolerance_changed` can never carry a model actor, because a
-- generated call may not reach a hold release directly or transitively. That is the rule
-- of the house, enforced by the storage layer rather than promised by it.

-- Structured detail, never a narrative paragraph: a flat map of scalars. A nested object
-- or an array is where prose would eventually be smuggled in.
CREATE FUNCTION holdfast_detail_is_flat(d jsonb) RETURNS boolean
  LANGUAGE sql IMMUTABLE PARALLEL SAFE
  AS $fn$
    SELECT coalesce(
      d IS NOT NULL
      AND jsonb_typeof(d) = 'object'
      AND NOT EXISTS (
            SELECT 1
            FROM jsonb_each(d) AS kv
            WHERE jsonb_typeof(kv.value) IN ('object', 'array')
          ),
      false);
  $fn$;

COMMENT ON FUNCTION holdfast_detail_is_flat(jsonb) IS
  'Journal detail is a flat map of scalars. Nesting is refused, because that is where prose arrives.';

CREATE TABLE audit_journal (
  id              TEXT          PRIMARY KEY,

  -- Monotonic per journal. Gaps are detectable.
  sequence        BIGINT        GENERATED BY DEFAULT AS IDENTITY,

  occurred_at     TIMESTAMPTZ   NOT NULL,
  recorded_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),

  -- Actor, flattened from the discriminated union.
  actor_kind      actor_kind    NOT NULL,
  actor_reviewer  TEXT,
  actor_component TEXT,
  actor_model_id  TEXT,
  actor_call_site llm_call_site,

  event           audit_event   NOT NULL,

  -- EntityRef. Polymorphic by design: eight entity kinds, one journal.
  entity_kind     entity_kind   NOT NULL,
  entity_id       TEXT          NOT NULL,

  run_id          TEXT          REFERENCES runs (id),
  case_id         TEXT,

  detail          JSONB         NOT NULL DEFAULT '{}'::jsonb,

  payload_hash    TEXT          NOT NULL,
  prev_hash       TEXT,

  CONSTRAINT audit_journal_id_present     CHECK (btrim(id) <> ''),
  CONSTRAINT audit_journal_entity_present CHECK (btrim(entity_id) <> ''),
  CONSTRAINT audit_journal_sequence_positive CHECK (sequence >= 1),
  CONSTRAINT audit_journal_detail_flat    CHECK (holdfast_detail_is_flat(detail)),

  CONSTRAINT audit_journal_payload_hash_sha CHECK (holdfast_is_sha256(payload_hash)),
  CONSTRAINT audit_journal_prev_hash_sha    CHECK (prev_hash IS NULL OR holdfast_is_sha256(prev_hash)),

  -- Exactly one row begins the chain, and every later row names its predecessor.
  CONSTRAINT audit_journal_chain_is_unbroken CHECK (sequence = 1 OR prev_hash IS NOT NULL),

  -- An entry is recorded at or after the instant it describes.
  CONSTRAINT audit_journal_recorded_after_occurred CHECK (recorded_at >= occurred_at),

  -- The Actor union: each kind carries its own fields and no other kind's.
  CONSTRAINT audit_journal_actor_is_one_kind CHECK (
    CASE actor_kind
      WHEN 'human' THEN
        actor_reviewer IS NOT NULL AND btrim(actor_reviewer) <> ''
        AND actor_component IS NULL AND actor_model_id IS NULL AND actor_call_site IS NULL
      WHEN 'system' THEN
        actor_component IS NOT NULL AND btrim(actor_component) <> ''
        AND actor_reviewer IS NULL AND actor_model_id IS NULL AND actor_call_site IS NULL
      WHEN 'model' THEN
        actor_model_id IS NOT NULL AND btrim(actor_model_id) <> ''
        AND actor_call_site IS NOT NULL
        AND actor_reviewer IS NULL AND actor_component IS NULL
    END
  ),

  -- THE RULE OF THE HOUSE. A model actor may only ever appear on the events its own call
  -- site produces. No model actor can be recorded against a hold release, a decision, a
  -- tolerance change or a completed run — not by a bug, not by a later worker, not at all.
  CONSTRAINT audit_journal_model_actor_may_only_propose CHECK (
    actor_kind <> 'model'
    OR (
      (actor_call_site = 'ingestion_normalisation'
        AND event IN ('invoice_ingested', 'payment_ingested'))
      OR
      (actor_call_site = 'residual_proposal'
        AND event IN ('proposal_received', 'proposal_discarded'))
    )
  ),

  -- A release is always attributable to a person or to the system, never to a model.
  CONSTRAINT audit_journal_release_has_named_actor CHECK (
    event <> 'hold_released' OR actor_kind IN ('human', 'system')
  )
);

-- Monotonic and gap-visible: a missing sequence number is a missing row, and no two rows
-- may claim the same predecessor, so the chain cannot fork unnoticed.
CREATE UNIQUE INDEX audit_journal_sequence_uq  ON audit_journal (sequence);
CREATE UNIQUE INDEX audit_journal_prev_hash_uq ON audit_journal (prev_hash) WHERE prev_hash IS NOT NULL;

CREATE INDEX audit_journal_entity_idx   ON audit_journal (entity_kind, entity_id);
CREATE INDEX audit_journal_run_idx      ON audit_journal (run_id) WHERE run_id IS NOT NULL;
CREATE INDEX audit_journal_case_idx     ON audit_journal (case_id) WHERE case_id IS NOT NULL;
CREATE INDEX audit_journal_event_idx    ON audit_journal (event, occurred_at DESC);
CREATE INDEX audit_journal_occurred_idx ON audit_journal (occurred_at DESC);

-- The evidence-of-review export reads this: every generated call that was made, and what
-- became of the proposal it produced.
CREATE INDEX audit_journal_model_actor_idx ON audit_journal (occurred_at DESC)
  WHERE actor_kind = 'model';

COMMENT ON TABLE  audit_journal IS 'Append-only journal. UPDATE and DELETE are revoked on this table in 011 and the revocation is asserted by pnpm migrate.';
COMMENT ON COLUMN audit_journal.sequence IS 'Monotonic per journal. Gaps are detectable.';
COMMENT ON COLUMN audit_journal.prev_hash IS 'The previous row payload hash. Unique, so the chain cannot fork.';
COMMENT ON COLUMN audit_journal.detail IS 'Structured detail. A flat map of scalars, never a narrative paragraph.';
COMMENT ON COLUMN audit_journal.actor_call_site IS 'The only two places a generated call may sit. Constrained to proposal and ingestion events.';
