"use client";
import { useState } from "react";
import type { ExceptionDetail, ResolutionPath, RoutingDecisionInput } from "@/lib/api";
import type { PendingAction } from "@/hooks/useExceptionDetail";
import { formatDateTime } from "@/lib/format";
import { RESOLUTION_PATH_LABELS } from "@/lib/labels";
import { Button } from "@/components/ui/Button";
export function DecisionPanel({ exception, pending, error, onRoute }: { exception: ExceptionDetail; pending: PendingAction; error: string | null; onRoute: (input: RoutingDecisionInput) => Promise<boolean> }) {
  const [resolution_path, setPath] = useState<ResolutionPath>("internal_correction"); const [owner_next, setOwner] = useState(""); const [reason, setReason] = useState("");
  if (exception.routingDecision) { const d = exception.routingDecision; return <div className="border-l-2 border-positive px-4 py-4"><p className="text-[10px] font-medium tracking-wider text-ink-faint uppercase">Action routed</p><p className="mt-2 text-sm font-medium text-positive">{RESOLUTION_PATH_LABELS[d.resolution_path]}</p><dl className="mt-3 space-y-2 text-sm"><div><dt className="text-xs text-ink-faint">Next owner</dt><dd className="font-mono text-ink">{d.owner_next}</dd></div><div><dt className="text-xs text-ink-faint">Reason</dt><dd className="text-ink-muted">{d.reason}</dd></div></dl><p className="mt-3 font-mono text-[11px] text-ink-faint">{formatDateTime(d.routedAt)}</p></div>; }
  const valid = Boolean(owner_next.trim() && reason.trim());
  return <form className="space-y-3 px-4 py-4" onSubmit={async (event) => { event.preventDefault(); if (valid && await onRoute({ resolution_path, owner_next: owner_next.trim(), reason: reason.trim() })) { setOwner(""); setReason(""); } }}><p className="rounded-md border border-caution/30 bg-caution/8 px-3 py-2 text-xs text-ink-muted">Choose the next operational action. This does not determine whether the match is correct.</p><label className="block text-xs text-ink-muted">Resolution path<select required value={resolution_path} onChange={(e) => setPath(e.target.value as ResolutionPath)} className="mt-1.5 h-9 w-full rounded-md border border-line-strong bg-surface-2 px-2.5 text-sm text-ink focus:border-brand focus:outline-none">{Object.entries(RESOLUTION_PATH_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-xs text-ink-muted">Next owner<input required value={owner_next} onChange={(e) => setOwner(e.target.value)} placeholder="Team or operator" className="mt-1.5 h-9 w-full rounded-md border border-line-strong bg-surface-2 px-2.5 text-sm text-ink focus:border-brand focus:outline-none" /></label><label className="block text-xs text-ink-muted">Reason<textarea required value={reason} onChange={(e) => setReason(e.target.value)} rows={3} placeholder="Evidence-based routing reason" className="mt-1.5 w-full rounded-md border border-line-strong bg-surface-2 px-2.5 py-2 text-sm text-ink focus:border-brand focus:outline-none" /></label>{error ? <p role="alert" className="text-xs text-negative">{error}</p> : null}<Button type="submit" className="w-full" loading={pending === "route"} disabled={!valid || pending !== null}>Route action</Button></form>;
}
