import type { Signal } from "@/lib/api";
import { cn } from "@/lib/cn";
import { formatEvidenceValue } from "@/lib/format";
import { SignalBadge } from "@/components/ui/Badge";
import { ConfidenceMeter } from "@/components/ui/ConfidenceMeter";
const ORDER = { fail: 0, warn: 1, unknown: 2, pass: 3 } as const;
const score = (signal: Signal) => /match|similarity/i.test(signal.label) && signal.observed.kind === "integer" && signal.observed.unit === "%" ? signal.observed.value / 100 : null;
export function SignalTable({ signals }: { signals: Signal[] }) {
  if (!signals.length) return <p className="px-4 py-6 text-sm text-ink-faint">No field evidence supplied.</p>;
  const ordered = [...signals].sort((a,b) => ORDER[a.status] - ORDER[b.status]);
  const delta = ordered.find((s) => s.status === "fail" && /variance|delta|difference/i.test(s.label));
  return <div>{delta ? <div className="grid gap-3 border-b border-negative/25 bg-negative/6 px-4 py-3 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="text-[10px] font-medium tracking-wider text-negative uppercase">Amount delta</p><p className="mt-1 text-sm text-ink">{delta.label}</p></div><div><p className="text-[10px] uppercase text-ink-faint">Observed</p><p className="mt-0.5 font-mono text-lg font-semibold text-negative">{formatEvidenceValue(delta.observed)}</p></div><div><p className="text-[10px] uppercase text-ink-faint">Allowed</p><p className="mt-0.5 font-mono text-sm text-ink">{formatEvidenceValue(delta.expected)}</p></div></div> : null}
    <ul className="divide-y divide-line/60 sm:hidden">{ordered.map((s) => { const value = score(s); return <li key={s.id} className={cn("px-4 py-3", s.status === "fail" && "bg-negative/4")}><div className="flex justify-between gap-3"><div><p className="text-sm text-ink">{s.label}</p><p className="mt-0.5 font-mono text-[10px] text-ink-faint">{s.source}</p></div><SignalBadge status={s.status}/></div><dl className="mt-3 grid grid-cols-2 gap-3"><div><dt className="text-[10px] uppercase text-ink-faint">Source</dt><dd className="mt-1 text-sm text-ink">{formatEvidenceValue(s.observed)}</dd></div><div><dt className="text-[10px] uppercase text-ink-faint">Reference</dt><dd className={cn("mt-1 text-sm", s.expected ? "text-ink-muted" : "text-caution")}>{formatEvidenceValue(s.expected)}</dd></div></dl>{value !== null ? <div className="mt-3"><ConfidenceMeter value={value}/><p className="mt-1 text-[10px] text-ink-faint">Vendor match score · {formatEvidenceValue(s.observed)} · required {formatEvidenceValue(s.expected)}</p></div> : null}</li>; })}</ul>
    <div className="hidden overflow-x-auto sm:block"><table className="w-full border-collapse text-sm"><thead><tr className="border-b border-line"><th className="px-4 py-2 text-left text-[11px] font-medium uppercase text-ink-faint">Field / source</th><th className="px-4 py-2 text-left text-[11px] font-medium uppercase text-ink-faint">Source value</th><th className="px-4 py-2 text-left text-[11px] font-medium uppercase text-ink-faint">Reference value</th><th className="px-4 py-2 text-left text-[11px] font-medium uppercase text-ink-faint">Evidence state</th></tr></thead><tbody>{ordered.map((s) => { const value=score(s); return <tr key={s.id} className={cn("border-b border-line/60 last:border-b-0",s.status==="fail"&&"bg-negative/4")}><td className="px-4 py-2.5"><span className="block text-ink">{s.label}</span><span className="font-mono text-[11px] text-ink-faint">{s.source}</span></td><td className="px-4 py-2.5 text-ink-muted">{formatEvidenceValue(s.observed)}{value!==null?<div className="mt-1.5 max-w-36"><ConfidenceMeter value={value}/></div>:null}</td><td className={cn("px-4 py-2.5",s.expected?"text-ink-faint":"text-caution")}>{formatEvidenceValue(s.expected)}</td><td className="px-4 py-2.5"><SignalBadge status={s.status}/></td></tr>; })}</tbody></table></div>
  </div>;
}
