"use client";
import { useState } from "react";
import type { ChangeToleranceInput, ToleranceContext } from "@/lib/api";
import type { PendingAction } from "@/hooks/useExceptionDetail";
import { Button } from "@/components/ui/Button";
export function TolerancePanel({ tolerance, pending, error, onChange }: { tolerance: ToleranceContext; pending: PendingAction; error: string | null; onChange: (input: ChangeToleranceInput) => Promise<boolean> }) {
  const [to, setTo] = useState(String(tolerance.to)); const [reason, setReason] = useState(""); const next = Number(to); const valid = Number.isInteger(next) && reason.trim().length > 0;
  return <form className="space-y-3 px-4 py-4" onSubmit={async (e) => { e.preventDefault(); if (valid && await onChange({ from: tolerance.from, to: next, scope: tolerance.scope, reason: reason.trim() })) setReason(""); }}><p className="break-all font-mono text-[11px] text-ink-faint">{tolerance.scope}</p><div className="grid grid-cols-2 gap-3"><label className="text-xs text-ink-muted">Current<input readOnly value={tolerance.from} className="mt-1.5 h-9 w-full rounded-md border border-line bg-surface-2 px-2.5 font-mono text-sm text-ink-faint" /></label><label className="text-xs text-ink-muted">New integer value<input required type="number" step="1" value={to} onChange={(e) => setTo(e.target.value)} className="mt-1.5 h-9 w-full rounded-md border border-line-strong bg-surface-2 px-2.5 font-mono text-sm text-ink focus:border-brand focus:outline-none" /></label></div><label className="block text-xs text-ink-muted">Change reason<textarea required rows={2} value={reason} onChange={(e) => setReason(e.target.value)} className="mt-1.5 w-full rounded-md border border-line-strong bg-surface-2 px-2.5 py-2 text-sm text-ink focus:border-brand focus:outline-none" /></label>{error ? <p role="alert" className="text-xs text-negative">{error}</p> : null}<Button type="submit" variant="outline" className="w-full" loading={pending === "change_tolerance"} disabled={!valid || pending !== null}>Change tolerance</Button></form>;
}
