/**
 * HOLD REGISTRY — orchestrator-owned and FROZEN.
 *
 * Three workers build hold families in parallel (W05a duplicate, W05b variance,
 * W05c cardinality). Without a pre-existing entry point they would each invent one, all
 * three would edit the same file, and the parallelism bought by splitting W05 would be
 * spent resolving the collision. So the entry point exists before any of them start, and
 * none of them may edit it.
 *
 * A family exports an applicator from its own directory. The orchestrator wires it in
 * below at the Wave 3 merge gate. If you are a worker reading this: add your applicator to
 * YOUR directory, export it, and report the export path. Do not edit this file — the
 * ownership gate denies it before the scope check runs (quarantine Q1).
 *
 * The policy table is here rather than in each family because a hold's policy is a
 * DOMAIN fact, not an implementation detail. Whether a hold auto-releases, and whether
 * accounting entries may be created while it is on, mirrors Oracle Payables — and the
 * worker that raises a hold should not also be the one deciding it can be released
 * without a human. That separation is the same principle as freezing the amount cap in
 * eval/thresholds.json rather than in the code that enforces it.
 */

import { cardinalityFamily } from './cardinality';
import { duplicateFamily } from './duplicate';
import { matchingFamily } from './matching';
import { varianceFamily } from './variance';
import type {
  CaseId,
  Conflict,
  ConflictSeverity,
  HoldPolicy,
  HoldType,
  Invoice,
  InvoiceId,
  MatchCandidate,
  Payment,
  RunId,
} from '@/lib/types';
import { HOLD_TYPES } from '@/lib/types';

// ─────────────────────────────────────────────────────────────────────────────
// Policy — one slot per HoldType. Adding a hold type is a contract change.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * `blocks_accounting: false` means the invoice cannot be PAID but accrual entries may
 * still be created. That distinction is Oracle's, and carrying it is a large part of why
 * this reads as an AP system rather than a match flag.
 *
 * `auto_releasable: true` means the hold clears when the underlying condition resolves,
 * with no human involved. Everything else requires a named reviewer and a reason —
 * enforced at the type level by `ReleasedHold` in the contract.
 */
export const HOLD_POLICY: Readonly<Record<HoldType, HoldPolicy>> = Object.freeze({
  matching: {
    type: 'matching',
    auto_releasable: true,
    blocks_accounting: false,
    default_severity: 'material',
    clause: 'No payment matched within tolerance.',
  },
  price_variance: {
    type: 'price_variance',
    auto_releasable: false,
    blocks_accounting: false,
    default_severity: 'material',
    clause: 'Unit price differs from the purchase order beyond tolerance.',
  },
  quantity_variance: {
    type: 'quantity_variance',
    auto_releasable: false,
    blocks_accounting: false,
    default_severity: 'material',
    clause: 'Quantity billed differs from quantity received beyond tolerance.',
  },
  tax_variance: {
    type: 'tax_variance',
    auto_releasable: false,
    blocks_accounting: true,
    default_severity: 'blocking',
    clause: 'Tax amount differs beyond the percentage tolerance.',
  },
  tax_amount_range: {
    type: 'tax_amount_range',
    auto_releasable: false,
    blocks_accounting: true,
    default_severity: 'blocking',
    clause: 'Tax amount falls outside the permitted absolute range.',
  },
  dist_variance: {
    type: 'dist_variance',
    auto_releasable: false,
    blocks_accounting: true,
    default_severity: 'blocking',
    clause: 'Distribution total does not equal the invoice total.',
  },
  duplicate_candidate: {
    // Never auto-releasable. A duplicate payment is an overpayment and a fraud control,
    // and duplicates concentrate in a few high-value invoices — which is the whole reason
    // the amount cap exists. Releasing one silently is the failure this project exists to
    // prevent.
    type: 'duplicate_candidate',
    auto_releasable: false,
    blocks_accounting: true,
    default_severity: 'blocking',
    clause: 'A prior invoice matches on vendor, amount and date.',
  },
  no_reference: {
    type: 'no_reference',
    auto_releasable: true,
    blocks_accounting: false,
    default_severity: 'material',
    clause: 'No usable reference token was found on the payment side.',
  },
  cardinality_residual: {
    type: 'cardinality_residual',
    auto_releasable: false,
    blocks_accounting: false,
    default_severity: 'material',
    clause: 'A residual remains after partial settlement of a bulk payment.',
  },
  period_deferral: {
    type: 'period_deferral',
    auto_releasable: true,
    blocks_accounting: true,
    default_severity: 'advisory',
    clause: 'Invoice date and receipt date fall in different periods.',
  },
  credit_note_crossing: {
    type: 'credit_note_crossing',
    auto_releasable: false,
    blocks_accounting: true,
    default_severity: 'material',
    clause: 'A credit note crosses the settlement being matched.',
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// The family interface — what each of W05a/b/c exports
// ─────────────────────────────────────────────────────────────────────────────

/** Everything a family may see. Deliberately excludes the answer key. */
export interface HoldContext {
  readonly run_id: RunId;
  readonly case_id: CaseId;
  readonly invoice: Invoice;
  /** Payments in the date window, already normalised. */
  readonly payments: readonly Payment[];
  /** Ranked candidates from engine/match, read-only. */
  readonly candidates: readonly MatchCandidate[];
  /** Every other invoice in the run — duplicate detection runs over invoices. */
  readonly ledger: readonly Invoice[];
  /** Frozen policy constants from eval/thresholds.json (`policy` block only). */
  readonly policy: {
    readonly amount_cap_paise: number;
    readonly date_window_days: number;
    readonly max_subset_size: number;
  };
}

/**
 * A family proposes holds. It does not release them, and it does not decide a case.
 * `conflicts` may not be empty: every held invoice must carry at least one conflict, and
 * a hold with none is a policy bug that fails loudly rather than emitting an empty array.
 */
export interface HoldProposal {
  readonly invoice_id: InvoiceId;
  readonly type: HoldType;
  readonly reason: string;
  readonly severity: ConflictSeverity;
  readonly conflicts: readonly Conflict[];
}

export interface HoldFamily {
  /** Stable id, matching the owning worker: 'duplicate' | 'variance' | 'cardinality'. */
  readonly id: string;
  /** The hold types this family is permitted to raise. */
  readonly handles: readonly HoldType[];
  readonly apply: (ctx: HoldContext) => readonly HoldProposal[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Wiring — the orchestrator fills this at the Wave 3 merge gate
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Populated by the orchestrator once W05a, W05b and W05c have merged. Kept as an explicit
 * list rather than a side-effecting `register()` call so that the set of active families
 * is readable in one place and cannot depend on module import order.
 */
const FAMILIES: readonly HoldFamily[] = [
  duplicateFamily,   // W05a — over invoices, before matching. An overpayment control.
  varianceFamily,    // W05b — deltas classified by cause; tax splits by tolerance TYPE.
  cardinalityFamily, // W05c — bounded subset-sum; an empty set rather than a guess on a tie.
  // W05d — `matching` and `no_reference`. Added after the assembled engine was first
  // measured and both types showed 0.0 recall: the original three briefs covered nine of
  // eleven hold types and these two had no owner. It speaks last and only where no other
  // family did, so it can never mask a sibling's stronger claim.
  matchingFamily,
];

export function registeredFamilies(): readonly HoldFamily[] {
  return FAMILIES;
}

/**
 * Runs every registered family and returns their proposals unchanged.
 *
 * Two invariants enforced here rather than trusted to each family:
 *  - a family may only raise hold types it declared in `handles`
 *  - a proposal must carry at least one conflict
 *
 * Both throw rather than filtering. A silently dropped hold is an invoice that gets paid,
 * and "fail loudly" is cheaper than that every time.
 */
export function applyAll(ctx: HoldContext): readonly HoldProposal[] {
  const out: HoldProposal[] = [];
  for (const family of FAMILIES) {
    for (const p of family.apply(ctx)) {
      if (!family.handles.includes(p.type)) {
        throw new Error(
          `hold registry: family "${family.id}" raised "${p.type}", which it does not declare in handles`
        );
      }
      if (p.conflicts.length === 0) {
        throw new Error(
          `hold registry: family "${family.id}" raised "${p.type}" with no conflict. ` +
            'Every held invoice must carry at least one conflict; an empty array is a policy bug.'
        );
      }
      out.push(p);
    }
  }
  return out;
}

/** Every hold type has exactly one policy slot. Checked at module load, not in a test. */
for (const t of HOLD_TYPES) {
  if (!HOLD_POLICY[t]) throw new Error(`hold registry: no policy declared for hold type "${t}"`);
}
