// Orchestrator-owned. Deterministic tree hashing, shared by freeze/verify.
//
// The dataset hash is what lets us say "frozen at a named commit" and mean it. It has to
// be stable across machines, so: sort paths, hash raw bytes (never decoded text, which
// would make line endings load-bearing on Windows), and hash the listing itself.

import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

export const MANIFEST_NAME = 'MANIFEST';

export function sha256(buf) {
  return createHash('sha256').update(buf).digest('hex');
}

function walk(dir, out = []) {
  for (const e of readdirSync(dir).sort()) {
    const full = join(dir, e);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

/**
 * Hash every file under `dir`, excluding the manifest itself.
 * Returns { files: [{ path, sha256 }], root } with `path` POSIX-relative to `dir`.
 */
export function hashTree(dir) {
  if (!existsSync(dir)) return null;
  const files = walk(dir)
    .map((f) => ({ abs: f, path: relative(dir, f).split(sep).join('/') }))
    .filter((f) => f.path !== MANIFEST_NAME)
    .sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
    .map((f) => ({ path: f.path, sha256: sha256(readFileSync(f.abs)) }));

  const listing = files.map((f) => `${f.sha256}  ${f.path}`).join('\n');
  return { files, root: sha256(Buffer.from(listing, 'utf8')) };
}

export function renderManifest({ files, root }, meta) {
  const lines = [
    '# HOLDFAST DATA MANIFEST',
    '# Generated by `pnpm freeze`. Do not hand-edit — CI recomputes this on every PR.',
    '# A drift between this file and data/ is quarantine trigger Q7.',
    `# frozen_at: ${meta.frozenAt}`,
    `# commit:    ${meta.commit}`,
    `# files:     ${files.length}`,
    `# root:      ${root}`,
    '',
    ...files.map((f) => `${f.sha256}  ${f.path}`),
    '',
  ];
  return lines.join('\n');
}

export function parseManifest(text) {
  const root = /^# root:\s*([0-9a-f]{64})$/m.exec(text);
  const frozenAt = /^# frozen_at:\s*(.+)$/m.exec(text);
  const commit = /^# commit:\s*(.+)$/m.exec(text);
  const files = [];
  for (const line of text.split(/\r?\n/)) {
    const m = /^([0-9a-f]{64})\s\s(.+)$/.exec(line);
    if (m) files.push({ sha256: m[1], path: m[2] });
  }
  return {
    root: root ? root[1] : null,
    frozenAt: frozenAt ? frozenAt[1].trim() : null,
    commit: commit ? commit[1].trim() : null,
    files,
  };
}
